Repository jupyterhub/repo2docker, pull requests merged in 2019-09, with the labels that each got.

#777 include repo2docker version in docker tags
  Dockerfile
  hooks/post_push
Labels: workflow:needs-review

#727 include full docker progress events in push progress events
  repo2docker/app.py
Labels: workflow:needs-review

#779 add explicit log message on failing Docker connection
  repo2docker/app.py
  tests/unit/test_app.py
  tests/unit/test_argumentvalidation.py
  tests/unit/test_subdir.py
Labels: workflow:needs-review

#517 Provide help text for commandline arguments
  repo2docker/__main__.py
Labels: workflow:needs-update

#739 [MRG] Dataverse content provider
  MANIFEST.in
  repo2docker/app.py
  repo2docker/contentproviders/__init__.py
  repo2docker/contentproviders/dataverse.json
  repo2docker/contentproviders/dataverse.py
  setup.py
  tests/unit/contentproviders/test_dataverse.py
Labels: workflow:wip

#772 [MRG] Add support for installing different versions of R
  docs/source/config_files.rst
  docs/source/faq.rst
  repo2docker/buildpacks/r.py
  tests/unit/test_r.py
Labels: workflow:wip
