Repository jupyterhub/repo2docker, pull requests merged in 2022-10, with the labels that each got.

#1185 Use enum to standardise `phase`
  repo2docker/__main__.py
  repo2docker/app.py
  repo2docker/contentproviders/git.py
  repo2docker/contentproviders/mercurial.py
  repo2docker/utils.py
Labels: maintenance

#1165 Bump default R version to 4.2 from 4.1, and let R 3.4 go from 3.4.0 to 3.4.4
  repo2docker/buildpacks/r.py
  tests/r/simple/verify
  tests/unit/test_r.py
Labels: maintenance, dependencies

#1186 ci: general refresh of github workflows, update gha versions and let dependabot do it, etc.
  .github/dependabot.yml
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  dev-requirements.txt
Labels: ci

#1204 run submodule test over https
  tests/conftest.py
  tests/unit/contentproviders/test_git.py
Labels: maintenance

#1197 docs: add devenv, linkcheck, and refresh misc config etc
  .gitignore
  .gitpod.yml
  .readthedocs.yaml
  docs/Makefile
  docs/doc-requirements.txt
  docs/make.bat
  docs/requirements.txt
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/contributing/contributing.md
  docs/source/contributing/tasks.md
  readthedocs.yml
Labels: documentation

#918 allow user to specify a single port with default command
  repo2docker/__main__.py
  repo2docker/app.py
  repo2docker/utils.py
  tests/unit/test_args.py
  tests/unit/test_ports.py
Labels: new

#976 Allow REPO_DIR to be a non-existing folder by creating it and providing the user with permissions
  repo2docker/buildpacks/base.py
  tests/conda/r3.6-target-repo-dir-flag/verify.py
  tests/conftest.py
Labels: bug

#1199 Create wheels with the build package, stop calling setup.py directly
  .github/workflows/release.yml
  .github/workflows/test.yml
  dev-requirements.txt
Labels: maintenance

#1200 ci: stop running pre-commit in gha, rely on pre-commit.ci
  .github/workflows/test.yml
Labels: ci

#1208 pipfile: pass --clear flag, and do it separetely to not be ignored
  repo2docker/buildpacks/pipfile/__init__.py
Labels: maintenance

#1126 Add check-tmp step to local repo tests
  repo2docker/buildpacks/_r_base.py
  repo2docker/buildpacks/pipfile/__init__.py
  tests/check-tmp
  tests/conftest.py
  tests/venv/postBuild/postBuild
Labels: maintenance

#1209 ci: use non-deprecated codecov uploader
  .github/workflows/test.yml
  dev-requirements.txt
Labels: ci
