Repository jupyterhub/repo2docker, pull requests merged in 2023-04, with the labels that each got.

#1262 dependabot: monthly updates of github actions
  .github/dependabot.yaml
Labels: maintenance

#1259 Remove deprecated nteract_on_jupyter
  docs/source/contributing/tasks.md
  docs/source/howto/user_interface.rst
  repo2docker/buildpacks/conda/__init__.py
  repo2docker/buildpacks/conda/environment.py-3.10-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.10-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.10.yml
  repo2docker/buildpacks/conda/environment.py-3.11-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.11-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.11.yml
  repo2docker/buildpacks/conda/environment.py-3.7-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.7-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.7.yml
  repo2docker/buildpacks/conda/environment.py-3.8-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.8-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.8.yml
  repo2docker/buildpacks/conda/environment.py-3.9-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.9-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.9.yml
  repo2docker/buildpacks/conda/environment.yml
  tests/base/node/verify
Labels: maintenance, breaking

#1264 missing `f` in julia fetch error f-string
  repo2docker/buildpacks/julia/julia_project.py
Labels: bug
