Repository jupyterhub/repo2docker, pull requests merged in 2023-06, with the labels that each got.

#1281 Recreate changelog as markdown
  CHANGES.rst
  docs/source/changelog.md
  docs/source/changelog.rst
Labels: documentation

#1283 Relax pins to major versions and refreeze, introduce explicit jupyter_server v1 pin
  repo2docker/buildpacks/conda/environment.py-3.10-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.10-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.10.yml
  repo2docker/buildpacks/conda/environment.py-3.11-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.11-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.11.yml
  repo2docker/buildpacks/conda/environment.py-3.7-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.7-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.7.yml
  repo2docker/buildpacks/conda/environment.py-3.8-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.8-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.8.yml
  repo2docker/buildpacks/conda/environment.py-3.9-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.9-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.9.yml
  repo2docker/buildpacks/conda/environment.yml
Labels: maintenance

#1285 Microsoft killed MRAN, stop relying on it
  docs/source/config_files.rst
  docs/source/howto/languages.rst
  repo2docker/buildpacks/r.py
  tests/r/README.md
  tests/r/r3.6-mran/runtime.txt
  tests/r/r3.6-rspm/install.R
  tests/r/r3.6-rspm/runtime.txt
  tests/r/r3.6-rspm/verify
  tests/r/r4.0-mran/install.R
  tests/r/r4.0-mran/runtime.txt
  tests/r/r4.0-mran/verify
  tests/unit/test_r.py
Labels: maintenance, breaking

#1286 Add changelog for 2023.06.0
  docs/source/changelog.md
Labels: documentation

#1288 Update version of R available
  docs/source/faq.rst
Labels: documentation
