Repository jupyterhub/repo2docker, pull requests merged in 2024-05, with the labels that each got.

#1348 update postBuild tests without ipyleaflet
  tests/venv/binder-dir/binder/postBuild
  tests/venv/binder-dir/verify
  tests/venv/start/postBuild/postBuild
  tests/venv/start/postBuild/verify
Labels: ci

#1350 Remove support for deprecated Julia REQUIRE, Julia < 1.3
  docs/source/architecture.md
  docs/source/config_files.rst
  docs/source/faq.rst
  docs/source/specification.rst
  repo2docker/buildpacks/julia/install-repo-dependencies.jl
  repo2docker/buildpacks/julia/julia_require.py
  tests/julia/project-binder-dir/.binder/Project.toml
  tests/julia/project-binder-dir/Project.toml
  tests/julia/project-binder-dir/verify
  tests/julia/require-1-requirements-file/REQUIRE
  tests/julia/require-1-requirements-file/requirements.txt
  tests/julia/require-1-requirements-file/verify
  tests/julia/require/REQUIRE
  tests/julia/require/verify
Labels: breaking

#1351 fix julia semver tilde upper bounds
  repo2docker/semver.py
  tests/unit/test_semver.py
Labels: bug

#1340 [MRG] Update to JupyterLab 4
  repo2docker/buildpacks/conda/environment.py-3.10-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.10-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.10.yml
  repo2docker/buildpacks/conda/environment.py-3.11-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.11-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.11.yml
  repo2docker/buildpacks/conda/environment.py-3.12-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.12-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.12.yml
  repo2docker/buildpacks/conda/environment.py-3.8-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.8-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.8.yml
  repo2docker/buildpacks/conda/environment.py-3.9-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.9-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.9.yml
  repo2docker/buildpacks/conda/environment.yml
  repo2docker/buildpacks/conda/freeze.py
Labels: breaking
