Repository jupyterhub/repo2docker, pull requests merged in 2024-08, with the labels that each got.

#1364 update import of shlex.quote
  tests/conftest.py
Labels: maintenance

#1365 exclude defaults channel by default
  repo2docker/buildpacks/conda/install-base-env.bash
  tests/conda/downgrade/verify
Labels: enhancement

#1369 Refreeze conda packages (JupyterLab 4.2.3 -> 4.2.5)
  repo2docker/buildpacks/conda/environment.py-3.10-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.10-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.10.yml
  repo2docker/buildpacks/conda/environment.py-3.11-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.11-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.11.yml
  repo2docker/buildpacks/conda/environment.py-3.12-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.12-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.12.yml
  repo2docker/buildpacks/conda/environment.py-3.8-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.8-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.8.yml
  repo2docker/buildpacks/conda/environment.py-3.9-linux-64.lock
  repo2docker/buildpacks/conda/environment.py-3.9-linux-aarch64.lock
  repo2docker/buildpacks/conda/environment.py-3.9.yml
  tests/conda/py35-binder-dir/.binder/environment.yml
Labels: dependencies
