Repository jupyterhub/repo2docker, pull requests merged in 2025-02, with the labels that each got.

#1408 Don't run scheduled workflows on forks
  .github/workflows/test.yml
Labels: ci

#1409 `set -e` should not be set after conda environment is sourced
  repo2docker/buildpacks/conda/activate-conda.sh
  tests/venv/start/postBuild/README.rst
  tests/venv/start/postBuild/verify
Labels: bug

#1410 Add basic UI Playwright tests
  .github/workflows/test.yml
  playwright-requirements.txt
  tests/conftest.py
  tests/ui/README.md
  tests/ui/browser/environment.yml
  tests/ui/browser/external-verify
  tests/ui/browser/external-verify.py
  tests/ui/browser/test-extra-args.yaml
  tests/ui/browser/verify
Labels: ci

#1411 Require Python 3.9 to run repo2docker
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  repo2docker/buildpacks/base.py
  repo2docker/buildpacks/conda/__init__.py
  repo2docker/buildpacks/julia/julia_project.py
  repo2docker/buildpacks/nix/__init__.py
  repo2docker/buildpacks/pipfile/__init__.py
  repo2docker/buildpacks/python/__init__.py
  repo2docker/buildpacks/r.py
  repo2docker/semver.py
  setup.py
Labels: breaking

#1412 Bump alpine docker to 3.21
  Dockerfile
Labels: dependencies

#1402 Shell out to `docker buildx build` to build images
  repo2docker/__main__.py
  repo2docker/app.py
  repo2docker/docker.py
  tests/unit/test_app.py
  tests/unit/test_args.py
Labels: breaking
